export const pages = [
    //"1.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "recover.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "intro.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "fashion.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "ZintleExp.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "ZintlePro.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/Siyamthanda.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
   "modelers/Ano.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "modelers/Nako.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "modelers/Tandile.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
    "modelers/Timna.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
    "modelers/SihleGco.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
    "modelers/Lusanda.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
    "modelers/Thandiwe.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
    "modelers/Sihle.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
    "colorcov.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
    "colorcov.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
    "sample1.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
    "sample2.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
    "sample3.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
    "color_graph.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
    "19.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
    "backcover.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   /* "taylor-grote.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=1506",
    "BackCover.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",

   // "fashion.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
     "dna.png?auto=compress&cs=tinysrgb&dpr=1&w=100",
    "dna_cov.png?auto=compress&cs=tinysrgb&dpr=1&w=100",
    "catalogue.png?auto=compress&cs=tinysrgb&dpr=1&w=1506", */
   // "https://images.rawpixel.com/image_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIyLTA2L3M3MS1tY2tpbnNleS0xNDkxLWZvbi5qcGc.jpg?auto=compress&cs=tinysrgb&dpr=1&w=1506"
  ];