export const pages = [
    //"1.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "Impilo_cover.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "about.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "contents.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "editor_note.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "ad_impilo.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "Olio-Brands.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "Model.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "color_art.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "color_psy.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "color_psy2.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "color_psy3.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "color_graph.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
   "anon_model.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",

   //WISEK
"fashionshow/wiseK/WiseK_cover.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
"fashionshow/wiseK/WiseK_Pro.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
"fashionshow/wiseK/WiseK_art.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
"fashionshow/wiseK/wise_cover.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
"fashionshow/wiseK/wise_k_fashion.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
"fashionshow/wiseK/wise_k_fashion_gallery.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
"fashionshow/wiseK/wisek_fashion2.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
"fashionshow/wiseK/wisek_gall.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   //WISEK 
   "fashion_trends.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
   //MODELS//
"fashionshow/Shantel_cover.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
"fashionshow/Shantel_art.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
"fashionshow/Shantel_pg1.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
"fashionshow/Shantel_gall.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
  "fashionshow/Oratile_cover.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/Kendall.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/Ora_art.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/ora_gall.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/Bongi_cover.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/Bongi.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/Bongi_gallery.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/Milly_cover.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/Milly.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/milly_gallery.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/Jabu_cover.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/Jabu_lee.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/Jabulee_gall.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/Ntsiki_cover.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/Nonsikelelo.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/Ntsiki_gallery.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/Olwethu_cover.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/Olwethu.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/Lwethu_gallery.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/Fifi_cover.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/refilwe.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/Refilwe_gallery.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/Sphe_cover.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
    "fashionshow/Sphe.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
     "fashionshow/Siphe_gallery.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
     "fashionshow/Thoko_cover.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/Thoko.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/thoko_gallery.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/Tshepo_cover.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/Tshepo_Mahlangu.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "fashionshow/Tshepo_gallery.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   "sije.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
   //END OF MODELS

    "content/cover_cont.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "content/slogan.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "content/contents.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "content/welcome.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "content/objectives.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "content/break.png?auto=compress&cs=tinysrgb&dpr=1&w=1500", 
    "content/chapter1.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "content/unleash.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "content/clientele.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "content/goals.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "content/branding.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "content/slogan2.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "content/notes.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "content/chapter2.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "content/style.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "content/checklist.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "content/bizmodel.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "content/platform.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "content/project_cale.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "content/inspirations.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "content/credits.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "biz/biz_model.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "biz/welcome.png?auto=compress&cs=tinysrgb&d=1&w=1500",
    "biz/getting.png?auto=compress&cs=tinysrgb&d=1&w=1500",
    "biz/checklist.png?auto=compress&cs=tinysrgb&d=1&w=1500",
    "biz/brand_identity.png?auto=compress&cs=tinysrgb&d=1&w=1500",
    "biz/brand_insp.png?auto=compress&cs=tinysrgb&d=1&w=1500",
    "biz/targets.png?auto=compress&cs=tinysrgb&d=1&w=1500",
    "biz/milestones.png?auto=compress&cs=tinysrgb&d=1&w=1500",
    "biz/planner.png?auto=compress&cs=tinysrgb&d=1&w=1500",
    "biz/planner2.png?auto=compress&cs=tinysrgb&d=1&w=1500",
    "biz/monthly.png?auto=compress&cs=tinysrgb&d=1&w=1500",
    "biz/testimonials.png?auto=compress&cs=tinysrgb&d=1&w=1500",
    "biz/vote.png?auto=compress&cs=tinysrgb&d=1&w=1500",
  
  
  
   //"backcover.png?auto=compress&cs=tinysrgb&dpr=1&w=1500"
    /*"taylor-grote.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=1506",
    "BackCover.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",

   // "fashion.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
     "dna.png?auto=compress&cs=tinysrgb&dpr=1&w=100",
    "dna_cov.png?auto=compress&cs=tinysrgb&dpr=1&w=100",
    "catalogue.png?auto=compress&cs=tinysrgb&dpr=1&w=1506", */
   // "https://images.rawpixel.com/image_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIyLTA2L3M3MS1tY2tpbnNleS0xNDkxLWZvbi5qcGc.jpg?auto=compress&cs=tinysrgb&dpr=1&w=1506"
  ];