export const pages = [
    //"1.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "Impilomag.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "about.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "fashion.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/Zintle_cover.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/Zee.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/zintle_art.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/zintle_art2.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/zintle_album.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/zintle_album2.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/zintle_album3.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/dnm.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/gallery.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/asa.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/asande.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/avi.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/Avile.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/avile2.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/Khamisa.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/luks.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/Lukiwe.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/lum.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/lumi.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/lus.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/Lusanda.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/Naks.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/Nako.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/Maude.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
   
    "modelers/tandile.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/thandiwe.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/tim.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/timna.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
   
   /*  "modelers/Siyamthanda.png?auto=compress&cs=tinysrgb&dpr=1&w=1500 ",
   /* "modelers/Nako.png?auto=compress&cs=tinysrgb&dpr=1&w=1506", */
   /* "modelers/Tandile.png?auto=compress&cs=tinysrgb&dpr=1&w=1506", */
   /*  "modelers/Timna.png?auto=compress&cs=tinysrgb&dpr=1&w=1506", */
    "modelers/SihleGco.png?auto=compress&cs=tinysrgb&dpr=1&w=1506", 
    //"modelers/Lusanda.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
        "modelers/Sibabalo.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
    "modelers/Sihle.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
     "modelers/Siyamthanda.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/Soma.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
    "modelers/yonwabisa.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "modelers/Zihle.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
"modelers/Zimi.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
    "psycolor.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "color_psy.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "color_psy2.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "color_psy3.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
    "color_graph.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
   //"zintlePro.png?auto=compress&cs=tinysrgb&dpr=1&w=1500",
   "backcover.png?auto=compress&cs=tinysrgb&dpr=1&w=1506"
    /*"taylor-grote.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=1506",
    "BackCover.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",

   // "fashion.png?auto=compress&cs=tinysrgb&dpr=1&w=1506",
     "dna.png?auto=compress&cs=tinysrgb&dpr=1&w=100",
    "dna_cov.png?auto=compress&cs=tinysrgb&dpr=1&w=100",
    "catalogue.png?auto=compress&cs=tinysrgb&dpr=1&w=1506", */
   // "https://images.rawpixel.com/image_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIyLTA2L3M3MS1tY2tpbnNleS0xNDkxLWZvbi5qcGc.jpg?auto=compress&cs=tinysrgb&dpr=1&w=1506"
  ];